services:
  - type: web
    name: nairatag-web
    runtime: node
    plan: starter
    region: frankfurt
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: NT_SESSION_SECRET
        generateValue: true
      - key: NT_OTP_SECRET
        generateValue: true
      - key: NEXT_PUBLIC_PRIVY_APP_ID
        value: cm8s0beg200jbava4d5szjlyc
      - key: PRIVY_APP_ID
        value: cm8s0beg200jbava4d5szjlyc
      - key: PRIVY_APP_SECRET
        sync: false
      - key: PRIVY_JWT_VERIFICATION_KEY
        sync: false
      - key: MONO_PUBLIC_KEY
        sync: false
      - key: MONO_SECRET_KEY
        sync: false
      - key: MONO_BASE_URL
        value: https://api.withmono.com/v3
      - key: MONO_ENV
        value: sandbox
      - key: MONO_V4_ENV
        value: live
      - key: MONO_V4_CLIENT_ID
        sync: false
      - key: MONO_V4_CLIENT_SECRET
        sync: false
      - key: MONO_V4_ENCRYPTION_KEY
        sync: false
      - key: FLW_BASE_URL
        value: https://api.flutterwave.com/v3
      - key: FLW_PUBLIC_KEY
        sync: false
      - key: FLW_SECRET_KEY
        sync: false
      - key: FLW_SECRET_HASH
        sync: false
      - key: NT_PUBLIC_APP_URL
        sync: false
      - key: NT_ENS_CHAIN_ID
        sync: false
      - key: NT_ENS_PARENT_NAME
        sync: false
      - key: NT_ENS_MAINNET_RPC_URL
        sync: false
      - key: NT_ENS_REGISTRY_ADDRESS
        sync: false
      - key: NT_ENS_NAME_WRAPPER_ADDRESS
        sync: false
      - key: NT_ENS_SUBGRAPH_URL
        sync: false
      - key: NT_TELEGRAM_BOT_USERNAME
        sync: false
      - key: NT_TELEGRAM_BOT_TOKEN
        sync: false
      - key: NT_TELEGRAM_WEBHOOK_SECRET
        sync: false
      - key: NT_TELEGRAM_INGEST_SECRET
        sync: false
      - key: NT_TELEGRAM_CHANNEL_ID
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: NT_NOTIFICATION_WEBHOOK_URL
        sync: false
      - key: NT_NOTIFICATION_WEBHOOK_SECRET
        sync: false
      - key: NT_TRANSACTION_WEBHOOK_SECRET
        sync: false
